### ISSUE TITLE
Migration to version 12.0

### ISSUE THREAD

**Issue by jjscarafia** [ingadhoc/account-payment#138]
# Todo

https://github.com/OCA/maintainer-tools/wiki/Migration-to-version-12.0

# Modules to migrate

- [ ] account_check
- [ ] account_payment_fix
- [ ] account_payment_group
- [ ] account_payment_group_document
- [ ] account_payment_group_expense
- [ ] account_transfer_unreconcile
- [ ] account_withholding
- [ ] account_withholding_automatic
