### ISSUE TITLE
Migration to version 10.0

### ISSUE THREAD

**Issue by adhoc-transbot** [ingadhoc/account-payment#58]
# Todo

https://github.com/OCA/maintainer-tools/wiki/Migration-to-version-10.0

# Modules to migrate

- [x] account_check
- [x] account_payment_fix
- [ ] account_payment_group
- [x] account_payment_group_document
- [ ] account_transfer_unreconcile
- [x] account_withholding
- [ ] account_withholding_automatic
- [ ] payment_group
